
FROM websphere-liberty:webProfile7
# Install required features if not present
RUN installUtility install --acceptLicense --downloadDependencies=true JDBCSample
CMD ["/opt/ibm/docker/docker-server", "run", "JDBCSample"]
EXPOSE 9120
